variable "region" {
  type        = string
  default     = "ap-southeast-1"
  description = "AWS region"
}

variable "project" {
  type        = string
  default     = "caladan-work-sample"
  description = "Project name"
}

variable "ami_id" {
  type        = string
  default     = "ami-08e7e250e7e3deb9b"
  description = "Amazon EC2 AMI Locator (ap-southeast-1 / Noble Numbat / 24.04 LTS / amd64)"
}

variable "ami_id_first_server" {
  type        = string
  description = "AMI ID generated by Packer to be used for the first server"
}

variable "private_ip_first_server" {
  type        = string
  default     = "172.31.16.10"
  description = "Private IP for the first server"
}

variable "private_ip_second_server" {
  type        = string
  default     = "172.31.16.20"
  description = "Private IP for the second server"
}

variable "subnet_id" {
  type        = string
  default     = "subnet-0a7ff65d404bfbbfa"
  description = "Subnet VPC default: apse1-az1 (ap-southeast-1a)"
}

variable "instance_type" {
  type        = string
  default     = "t3a.medium"
  description = "EC2 instance type"
}

variable "whitelisted_ips" {
  type        = list(string)
  default     = ["14.169.109.148/32"]
  description = "Whitelisted IPs to access first server"
}
